import "../styles/globals.css";
import Head from "next/head";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Welcome to Girls Who Code TXST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" sizes="16x16" href="/asset.png" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
